### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by issqqqq** [yebei199/meow-memorizing#48]
作者你好，解压完下一步应该做什么？

**Comment by yebei199** [comment]
直接打开解压的文件就行了(づ￣ 3￣)づ
![chrome_IxSk8gFKxM](https://github.com/user-attachments/assets/0196a2b3-5954-4a54-a6ee-dfde514e7b47)

**Comment by issqqqq** [comment]
你好，我已收到你的来信在我阅读后会尽快回复你的

**Comment by yebei199** [comment]
> 我选择添加已解压的扩展程序后显示这个画面 ![微信截图_20240917200535](https://private-user-images.githubusercontent.com/97157134/368156630-cd05944a-5ade-4b26-a632-fd26e2d07e31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NzU2MDcsIm5iZiI6MTcyNjU3NTMwNywicGF0aCI6Ii85NzE1NzEzNC8zNjgxNTY2MzAtY2QwNTk0NGEtNWFkZS00YjI2LWE2MzItZmQyNmUyZDA3ZTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDEyMTUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3OTU4OTJjODcyNTcwY2Y2NGViMWEzZTI1MjBiM2QwMmI0YjE4NWU5ODg5NTFlMzdiMTgyZjMwOTI3Y2M0M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AEVVr-RQpgpDARn3cr5742-8d-BMrJUPeRQwhtZj9nU) 另外，我想问一下我这个自动回复要在哪里关闭啊

在github个人设置里可以关吧, 加载你要下release的包 https://github.com/yebei199/meow-memorizing/releases/tag/v0.1.8

**Comment by issqqqq** [comment]
谢谢你，我已经安装成功了，但是这个插件要如何使用啊？

**Comment by yebei199** [comment]
> 谢谢你，我已经安装成功了，但是这个插件要如何使用啊？

严格来说, 目前就一个功能, 鼠标选中一个单词就会高亮整个网页的这个单词, 其他功能, 我还没做ヾ(^▽^*)))

**Comment by issqqqq** [comment]
> 作者你好，解压完下一步应该做什么？

> 

>

**Comment by yebei199** [comment]
> 谢谢你，我已经安装成功了，但是这个插件要如何使用啊？



那你还有什么想要的功能吗?
